cicd

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -33,7 +33,7 @@ jobs:
 
     # Exécuter les tests avec Docker Compose
     - name: Run tests
-      run: docker-compose exec django python manage.py test polls || (echo "Tests failed, check logs"; docker-compose logs django)
+      run: docker exec django python pubmed_analyze/manage.py test pubmed_analyze/polls || (echo "Tests failed, check logs"; docker-compose logs django)
 
     # Étape pour arrêter les services après les tests
     - name: Stop services
